# Generated by Django 4.2.3 on 2023-07-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(upload_to='goods/%Y/%m/%d'),
        ),
    ]
