# Generated by Django 4.2.3 on 2023-07-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
