# Generated by Django 4.2.3 on 2023-08-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_good_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='image',
        ),
        migrations.AddField(
            model_name='good',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='goods.category'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.good')),
            ],
        ),
    ]
