# Generated by Django 4.2.3 on 2023-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_rename_product_images_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
