# Generated by Django 4.2.3 on 2023-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2023-07-14'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
